source:       app
baseurl:      "/global-services" 

markdown:   kramdown
permalink:  pretty
exclude:
  - assets/styles
  - README.md
  - font-generator
  - contributing
  
default_locale:     "en"
languages: ["en", "es"]
language_names:
  en: "English"
  es: "EspaÃ±ol"

collections_dir: services
collections:
  assessment:
    output: true
    en: 
      url: "/assessment/"
    es: 
      url: "/es/assessment/"
  basecamp:
    output: true
    en: 
      url: "/basecamp/"
    es: 
      url: "/es/basecamp/"
  cash:
    output: true
    en: 
      url: "/cash/"
    es: 
      url: "/es/cash/"
  cea:
    output: true
    en: 
      url: "/cea/"
    es: 
      url: "/es/cea/"
  comms:
    output: true
    en: 
      url: "/comms/"
    es: 
      url: "/es/comms/"
  drr:
    output: true
    en: 
      url: "/drr/"
    es: 
      url: "/es/drr/"
  health:
    output: true
    en: 
      url: "/health/"
    es: 
      url: "/es/salud/"
  hr:
    output: true
    en: 
      url: "/hr/"
    es: 
      url: "/es/hr/"
  im:
    output: true
    en: 
      url: "/infomgmt/"
    es: 
      url: "/es/im/"
  itt:
    output: true
    en: 
      url: "/itt/"
    es: 
      url: "/es/itt/"
  livelihoods:
    output: true
    en: 
      url: "/livelihoods/"
    es: 
      url: "/es/livelihoods/"
  logs:
    output: true
    en: 
      url: "/logistics/"
    es: 
      url: "/es/logistica/"
  opsmanagement:
    output: true
    en: 
      url: "/opsmanagement/"
    es: 
      url: "/es/opsmanagement/"
  pgi:
    output: true
    en: 
      url: "/pgi/"
    es: 
      url: "/es/pgi/"  
  pmer:
    output: true
    en: 
      url: "/pmer/"
    es: 
      url: "/es/pmer/"  
  relief:
    output: true
    en: 
      url: "/relief/"
    es: 
      url: "/es/relief/"  
  security:
    output: true
    en: 
      url: "/security/"
    es: 
      url: "/es/security/"
  shelter:
    output: true
    en: 
      url: "/shelter/"
    es: 
      url: "/es/shelter/"
  wash:
    output: true
    en: 
      url: "/wash/"
    es: 
      url: "/es/wash/"  
  zz_other:
    output: true
    en: 
      url: "/other/"
    es: 
      url: "/es/other/"
        